### ISSUE TITLE
Missing asymmetric version in the current target url

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/mist2templateflow#3]
In nilearn, download function grabs older version. Current link in this repo grabs newer version, but lacks asymmetric version. After verifying wit Pierre we confirmed the difference between the two versions is the name and resolution. We should use the old version as there's no difference between the two practically.

**Comment by htwangtw** [comment]
https://figshare.com/articles/dataset/Group_multiscale_functional_template_generated_with_BASC_on_the_Cambridge_sample/1285615
https://figshare.com/articles/dataset/MIST_A_multi-resolution_parcellation_of_functional_networks/5633638

here are the two versions

**Comment by htwangtw** [comment]
Resolved by commit [915f1ae](https://github.com/SIMEXP/mist2templateflow/commit/915f1ae60f04f6a4432ce4ca40fa0a70630c2aef).
According to Pierre they are the same, just the mist release has labels.
I added the old version and use BASC as altas name. 
We can close this issue for now so we have everything in one click.
We will think about the labelling issue in the future.
